# Generated by Django 4.2 on 2025-03-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_product_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_updated_date',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_created_date',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_updated_date',
        ),
    ]
