# Generated by Django 4.2 on 2025-03-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_product_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
